### ISSUE TITLE
Failure to push updated codes

### ISSUE THREAD

**Issue by paulinebanye** [ersilia-os/eos5505#1]
### Issues pushing changes to the repo

Hi @GemmaTuron, I am having issues uploading codes to my copy of this repo. I forked and cloned it but I have been struggling to push the codes. 

### Steps taken

- [x] Fork the eos5505 repo.
- [x] Clone the repo to obtain a copy on my GitHub.
- [x] Install git LFS on my local system. 
- [x] Initialize git LFS.
- [ ] It begins with uploading LFS object, then fails
<img width="538" alt="err0" src="https://user-images.githubusercontent.com/63536707/210707260-59e21b8b-5545-4070-9d6d-441a4a3283c8.png">

<img width="583" alt="err1" src="https://user-images.githubusercontent.com/63536707/210706763-ead7d749-8eb7-4a2c-ae5a-79b8c4d4d18b.png">

### Other attempts
In a bid to identify where the error is occurring from and if it is an issue related to my fork of the repo, I decided to:
- [x] I cloned the eos5505 repo directly
- [x] Created a new branch
- [ ] Push to the new branch, however due to restricted permissions, as expected, I received a `fatal: unable to access 'https://github.com/ersilia-os/eos5505.git` 

<img width="693" alt="err2" src="https://user-images.githubusercontent.com/63536707/210709139-e174c9da-e991-468f-b911-257e414846fa.png">

- [x] Separated the contents of the repo into individual files.
- [ ] Attempted to push the files individually to the repo but encountered the same error.
- [ ] Attempted with `git lfs push --all origin <branch_name>`

I am attempting to find a workaround for this. It seems to be  a relatively common issue but all suggestions I have tried have failed.

**Comment by GemmaTuron** [comment]
Hi @pauline-banye 

There is no workaround at the moment, I need to manually add the repositories to our github team and give you permits. I've done it for this repo already so this issue should be solved.
But before pushing to ersilia's github, you should test the model in your forked branch, which wouldn't give permit issues

**Comment by GemmaTuron** [comment]
Sorry, update from my part.
Git LFS does not allow commits on public forks for some reason, the best workaround therefore will be to work on branches as we are doing now
