### ISSUE TITLE
Flask in chemprop

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos5505#2]
Hi  @pauline-banye !

I have been doing some work in the model:

- The file I use to create the environment is the env_gt.yaml, I have removed many dependencies (it might crash if I removed something needed), and added protobuf 3.19.5 (instead of the default installed 4.2, which is incompatible with other dependencies)
- I have forced the torch install 1.6+cpu, you might need to add the following flag `-f https://download.pytorch.org/whl/torch-stable/`
- I have created some init files and made sure the sys.path.insert was redirecting to the right packages
- The conda environment now has the model name

At this stage, I am able to run the appb3.py up to the point where it fails at loading chemprop because it is still trying to use flask. How did you manage to run the appb3.py yesterday? I cannot reproduce these results.
I'll let you take it from here, try to reproduce my steps and investigate the current flask error. Please pull and create a conda environment again

**Comment by GemmaTuron** [comment]
Hi  @pauline-banye 
Great that you managed to run the appb3.py file. Can you list which dependencies did you install manually that were not specified in the yaml file so we can incorporate them?

**Comment by miquelduranfrigola** [comment]
This has been resolved. Closing issue
