### ISSUE TITLE
Test model eos5505 in CLI and Colab

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos5505#4]

**Comment by carcablop** [comment]
Hi @GemmaTuron. 
Testing the model in Google Colab. I have the same error like other models (eos935d, eos4q1a). I think the path is being assigned wrong somewhere when fetching the model, the path should be * `/usr/local/envs/eos5505/bin/python`. 
![imagen](https://user-images.githubusercontent.com/17841081/212691300-68bfa967-4b41-43ed-8ca8-83a88f5659cd.png)

**Comment by carcablop** [comment]
Following the path mentioned in the error: `output/root/eos/repository/eos5505/....../run_predict.sh` . I can see that in the run_predict file that the python path is being assigned wrong. 
![imagen](https://user-images.githubusercontent.com/17841081/212693950-2508c855-8f37-4bb6-8bf1-1c5a059cd72c.png)

**Comment by carcablop** [comment]
I attach the logs:
**Test in google colab:** Fail to fetch 
Log fetch: [Google_colab_log_fetch_eos5505.txt](https://github.com/ersilia-os/eos5505/files/10426608/Google_colab_log_fetch_eos5505.txt)

**Test in the CLI.** Fetch successfully, serve and predict.
Log fetch: 
[log_fetch_eos5505.txt](https://github.com/ersilia-os/eos5505/files/10426620/log_fetch_eos5505.txt)
Log predict:
[log_predict_eos5505.log](https://github.com/ersilia-os/eos5505/files/10426624/log_predict_eos5505.log)
Output predictions:  input file: "eml_canonicals.csv
[eos5505_output.csv](https://github.com/ersilia-os/eos5505/files/10426625/eos5505_output.csv)

**Comment by GemmaTuron** [comment]
Hi @carcablop and @pauline-banye 

The issue reported here and for the other models is due to this function from @carcablop pull request https://github.com/ersilia-os/ersilia/pull/525
    def get_python_path_env(self, environment):
        if not self.exists(environment):
            raise Exception("{0} environment does not exist".format(environment))
        python_path = subprocess.check_output("which python", shell=True).strip()
        index_env = python_path.decode("utf-8").find("envs/") + 5
        python_path_to_envs = python_path.decode("utf-8")[0:index_env]
        return "{0}{1}/bin/python".format(python_path_to_envs, environment)

As you can see the slash is probably cut at `python_path.decode("utf-8")[0:index_env]`.
We are now working on reformatting it.

**Comment by GemmaTuron** [comment]
We have modified the function here: https://github.com/ersilia-os/ersilia/commit/70bcf5469d912b86b469a3db9e2978f34ff7a1fe

The models are now working on Colab, can you try again?

**Comment by carcablop** [comment]
> Hola @carcablopy @pauline-banye
> 
> El problema informado aquí y para los otros modelos se debe a esta función de @carcablopsolicitud [ de extracción ersilia-os/ersilia#525 ](https://github.com/ersilia-os/ersilia/pull/525) def get_python_path_env(yo, entorno): si no self.exists (entorno): generar excepción ("{0} entorno no existe". formato (entorno)) python_path = subprocess.check_output("cuál python", shell=True).strip() index_env = python_path.decode("utf-8").find("envs/") + 5 python_path_to_envs = python_path.decode("utf-8")[0:index_env] devolver "{0}{1}/bin/python".format(python_path_to_envs, entorno)
> 
> Como puede ver, la barra probablemente esté cortada en `python_path.decode("utf-8")[0:index_env]`. Ahora estamos trabajando en reformatearla.

Hello @GemmaTuron . Thank you very much for the information. I'm so sorry this is causing the error.

**Comment by carcablop** [comment]
Update:
Test in google colab: Fetch successfully, serve and predict.
Log fetch: 
[log_fetch_colab_eos5505.txt](https://github.com/ersilia-os/eos5505/files/10427254/log_fetch_colab_eos5505.txt)
Output in colab:
[eos5505_output.csv](https://github.com/ersilia-os/eos5505/files/10427261/eos5505_output.csv)

**Comment by DhanshreeA** [comment]
The model works on CLI and Colab. Artifacts:

CLI Output:
[eos5505_output.csv](https://github.com/ersilia-os/eos5505/files/10456395/eos5505_output.csv)

Colab link: https://colab.research.google.com/drive/1jD2qTBAA3GUqD1-Iw5S_GuFmqC-pNjAN?usp=sharing

**Comment by GemmaTuron** [comment]
Perfect I'll mark this model as completed
