### ISSUE TITLE
Clean UP & Dockerization eos5505

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos5505#7]
Please check that the model is working and refactor it model to the latest eos-template structure.
The workflows have already been updated, you can start by checking if the Actions have run successfully or changes need to be made

**Comment by samuelmaina** [comment]
@GemmaTuron, there are only 2 workflow files for testing and testing on pr. I don't know if you intended the automation to include all the workflows.

**Comment by GemmaTuron** [comment]
@miquelduranfrigola can you try to run the update workflows on your side? it is telling me "everything up to date" but clearly it isn't

**Comment by samuelmaina** [comment]
@GemmaTuron  and @miquelduranfrigola  , I have refactored everything and was able to test with the eml data but I can't add  the other workflows to git. The only files recognized are the existing two.  I have restarted vs code, bash and the tracking is not possible.

**Comment by GemmaTuron** [comment]
that is very surprising indeed... let us try it again from our side.

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

The solution was very simple. I cloned the repo and tested adding one file, which returned the error that pointed me to the right direction:
```
git add .github/workflows/json-check.yml
The following paths are ignored by one of your .gitignore files:
.github
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
```
I have removed the `.github` from the `.gitignore` file. and now the files inside the `.github` folder can be git tracked normally

**Comment by GemmaTuron** [comment]
please check the current actions!

**Comment by samuelmaina** [comment]
Thanks very much. I use git UI in vs code for all git commands and it did not show this.  Checking  the actions now.

**Comment by samuelmaina** [comment]
@GemmaTuron please check the PR on minor modification of the scikit-learn version.  Able to fetch and predict the eml_canonical.csv.
 
[eos5505_cli_fetch.log](https://github.com/ersilia-os/eos5505/files/11832841/eos5505_cli_fetch.log)

[eos5505_cli_eml_pred.csv](https://github.com/ersilia-os/eos5505/files/11832842/eos5505_cli_eml_pred.csv)

**Comment by samuelmaina** [comment]
@GemmaTuron , I have observed a strange behavior with the test workflow, the test issue was opened before the PR was merged. Is this normal?

**Comment by GemmaTuron** [comment]
Hi @samuelmaina , the test issue was opened following my first PR updating the workflows. We [are working](https://github.com/ersilia-os/ersilia/issues/704) on avoiding the test issue being created several times
